### ISSUE TITLE
Why use this over the other package?

### ISSUE THREAD

**Issue by thorizer** [avdosev/tuple_dart#1]
this seems inspired from the [tuple](https://pub.dev/packages/tuple) package . 
any benefits for using this over the other ?

**Comment by avdosev** [comment]
@thorizer, I was inspired by this package. But my package has the following differences from the reference implementation:
1. My package is dependency free (google implementation depends on quiver)
2. Better support for functional programming due to the tuplized, detuplized methods for functions and the apply method (it's very useful)
3. Tuple2 implements the MapEntry interface, so you can use Map.fromEntries with Iterable\<Tuple2\> ([this issue](https://github.com/google/tuple.dart/issues/18) has still not been resolved google package for about three years)

Also consider looking at [itertools](https://pub.dev/packages/itertools) package (inspired by the python package), it contains zip (zip2, zip3, etc) and starmap (without suffix) methods, for even greater support for tuple from this package.
